### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/portalpadrao.release#23]
Ações para um novo release
---------------------------

- [x] Se a versão do Plone tiver sido alterada, favor indicar em https://github.com/plonegovbr/brasil.gov.portal#requisitos;
- [x] As dependências plonegovbr, se tiverem sofrido alteração, tem seus respectivos releases criados, tags geradas e pacotes disponibilizados no pypi;
    - [x] [brasil.gov.portal](https://github.com/plonegovbr/brasil.gov.portal/)
  - [x] [brasil.gov.tiles](https://github.com/plonegovbr/brasil.gov.tiles/)
  - [x] [brasil.gov.vcge 1.x](https://github.com/plonegovbr/brasil.gov.vcge/tree/1.0.x)
  - [x] [brasil.gov.vcge 2.x](https://github.com/plonegovbr/brasil.gov.vcge/)
  - [x] [brasil.gov.barra](https://github.com/plonegovbr/brasil.gov.barra/)
  - [x] [brasil.gov.portlets](https://github.com/plonegovbr/brasil.gov.portlets/)
  - [x] [brasil.gov.temas](https://github.com/plonegovbr/brasil.gov.temas/)
  - [x] [brasil.gov.agenda](https://github.com/plonegovbr/brasil.gov.agenda/)
  - [x] [brasil.gov.facetada](https://github.com/plonegovbr/brasil.gov.facetada/)
  - [x] [brasil.gov.paginadestaque](https://github.com/plonegovbr/brasil.gov.paginadestaque/)
- [x] Os releases de dependências plonegovbr feitas no passo anterior, as pinagens de dependências externas e do próprio Plone que foram testados durante o processo de geração de release são adicionadas/alteradas em https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg;
    - [x] [brasil.gov.portal](https://github.com/plonegovbr/brasil.gov.portal/)
  - [x] [brasil.gov.tiles](https://github.com/plonegovbr/brasil.gov.tiles/)
  - [x] [brasil.gov.vcge 1.x](https://github.com/plonegovbr/brasil.gov.vcge/tree/1.0.x)
  - [x] [brasil.gov.vcge 2.x](https://github.com/plonegovbr/brasil.gov.vcge/)
  - [x] [brasil.gov.barra](https://github.com/plonegovbr/brasil.gov.barra/)
  - [x] [brasil.gov.portlets](https://github.com/plonegovbr/brasil.gov.portlets/)
  - [x] [brasil.gov.temas](https://github.com/plonegovbr/brasil.gov.temas/)
  - [x] [brasil.gov.agenda](https://github.com/plonegovbr/brasil.gov.agenda/)
  - [x] [brasil.gov.facetada](https://github.com/plonegovbr/brasil.gov.facetada/)
  - [x] [brasil.gov.paginadestaque](https://github.com/plonegovbr/brasil.gov.paginadestaque/)
- [x] É feita uma revisão em todas as pinagens de https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg (procure por FIXME, HACK, BBB) para ver se poderá ser feita alguma modificação para aquele release em específico;
- [x] É feita uma revisão nas issues de https://github.com/plonegovbr/portalpadrao.release/ e https://github.com/plonegovbr/portal.buildout/ para ver se alguma melhoria pode ser incorporada no release;
- [x] Reiniciar as builds do master das dependências plonegovbr no travis, podendo ser todas ou apenas as alteradas para aquele release, ficando essa decisão por conta do responsável pelo release;
    - [x] [brasil.gov.portal](https://github.com/plonegovbr/brasil.gov.portal/)
  - [x] [brasil.gov.tiles](https://github.com/plonegovbr/brasil.gov.tiles/) (Corrigiu CI)
  - [x] [brasil.gov.vcge 1.x](https://github.com/plonegovbr/brasil.gov.vcge/tree/1.0.x) (Erro de code analysis; Isso não tem a ver com o escopo desse release e deve ser resolvido em https://github.com/plonegovbr/brasil.gov.vcge/issues/38)
  - [x] [brasil.gov.vcge 2.x](https://github.com/plonegovbr/brasil.gov.vcge/) (Erro de code analysis; Isso não tem a ver com o escopo desse release e deve ser resolvido em https://github.com/plonegovbr/brasil.gov.vcge/issues/38)
  - [x] [brasil.gov.barra](https://github.com/plonegovbr/brasil.gov.barra/) (O erro diz respeito ao js local não ser mais igual ao fornecido; Isso não tem a ver com o escopo desse release e deve ser resolvido em https://github.com/plonegovbr/brasil.gov.barra/issues/39)
  - [x] [brasil.gov.portlets](https://github.com/plonegovbr/brasil.gov.portlets/)
  - [x] [brasil.gov.temas](https://github.com/plonegovbr/brasil.gov.temas/)
  - [x] [brasil.gov.agenda](https://github.com/plonegovbr/brasil.gov.agenda/)
  - [x] [brasil.gov.facetada](https://github.com/plonegovbr/brasil.gov.facetada/)
  - [x] [brasil.gov.paginadestaque](https://github.com/plonegovbr/brasil.gov.paginadestaque/) (Necessária pequena alteração devido a atualização de collective.cover, ver https://github.com/plonegovbr/brasil.gov.paginadestaque/pull/13)
- [x] Criar uma instância da última versão de brasil.gov.portal e efetuar um teste exploratório mínimo;
- [x] Quando todas as revisões tiverem sido feitas e estiver para lançar um release, o https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg será copiado para https://github.com/plonegovbr/portalpadrao.release, de preferência numa nova branch, criando um novo diretório para aquele release (`wget https://raw.githubusercontent.com/plonegovbr/portal.buildout/master/buildout.d/versions.cfg`);
- [x] É feita uma alteração no `extends` de https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/base.cfg informando esse novo release criado (pode ser necessário esperar alguns minutos, pois a url http://downloads.plone.org.br/release/x.x.x/versions.cfg demora um tempo para sincronizar no github);
- [x] Verificar se a build do master de portal.buildout no travis está ok. Pode ser que ela quebre por não haver ainda o `versions-sem-extends.cfg`;
- [x] Criação das tags do release (esse é o **último** passo, é nessa ordem caso, durante os passos anteriores, seja necessária alguma alteração pontual):
    - [x] Gerar tag em https://github.com/plonegovbr/portal.buildout;
    - [x] Gerar o versions-sem-extends.cfg usando o script https://github.com/plonegovbr/portalpadrao.release/blob/master/versions-sem-extends.sh passando como parâmetro release gerado no passo anterior, e adicionar o arquivo gerado na pasta do release em https://github.com/plonegovbr/portalpadrao.release. Nesse momento, é interessante efetuar um diff no arquivo de versões do release anterior;
    - [x] Rodar o job do master de portal.buildout no travis com relação ao versions-sem-extends.cfg;
    - [x] Gerar tag em https://github.com/plonegovbr/portalpadrao.release;
- [x] Envio de email pelo patrocinador pra lista plonegovbr indicando o lançamento desse novo release. (Ele já foi avisado e na sequência fará o aviso)
